apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVVLQUFNNTZUV1FRQ09PV08KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0geGtmSVQ2aFlWT1lJQkl5eVloMDB4L0FGbjBnejJFMk1NT1UwSllpMAoK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

